server:
  port:
    8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://CHANGE:8761/eureka/

spring:
  rabbitmq:
    host: localhost
    port: 5672

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    #CHANGE HERE
    url: jdbc:postgresql://CHANGE.com:5432/postgres?current-schema=public
    username: postgres
    password: CHANGEME
    driverClassName: org.postgresql.Driver
    tomcat:
      defaultAutoCommit: false

  flyway:
    locations: classpath:/db-psql/migration,/db-psql/data/local

## Not necessary right now.
# jwt:
#   signingKey: ""
#   verifierKey: ""
##
