server:
  port:
    8083

spring:
  jpa:
    database: h2
    show-sql: false
    hibernate:
      ddlAuto: validate
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:rating-service
    driverClassName: org.h2.Driver
  flyway:
    locations: classpath:/db,/db/migration,/db/data/local
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/


## Not necessary right now.
# jwt:
#   signingKey: ""
#   verifierKey: ""
##
